name: cyclecoach
description: "Application mobile de suivi d'entra√Ænement v√©lo (CycleCoach)"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:   # ‚úÖ <-- AJOUT ICI !
    sdk: flutter

  # UI / Calendrier
  table_calendar: ^3.1.0

  # Stockage local
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2

  # Notifications
  flutter_local_notifications: ^17.1.0

  # Gestion d‚Äô√©tat simple
  provider: ^6.1.2

  # Ic√¥nes Cupertino iOS
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# üîΩ Configuration sp√©cifique √† Flutter
flutter:
  uses-material-design: true

  assets:
    - assets/logo/cyclecoach_logo.png

# üîΩ Configuration du package flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/cyclecoach_logo.png"
  adaptive_icon_background: "#0A192F" # bleu nuit
  adaptive_icon_foreground: "assets/logo/cyclecoach_logo.png"
